[env]
ORT_LIB_LOCATION = { value = ".", relative = true }

[unstable]
build-std = ["std"]

[build]
target = "wasm32-unknown-emscripten"
rustflags = [
    "-Clink-args=-fno-rtti -pthread -msimd128 -msse4.2 -sEXPORT_ALL -sSTACK_SIZE=5MB -sUSE_PTHREADS -sDEFAULT_PTHREAD_STACK_SIZE=2MB -sPTHREAD_POOL_SIZE=20 -sINITIAL_MEMORY=1GB -sEXPORT_ES6 --no-entry",
    "-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals"
]