[package]
publish = false
name = "example-wasm-emscripten"
version = "0.0.0"
edition = "2021"

[dependencies]
ort = { path = "../../" }
ndarray = "0.16"
rust-embed = { version = "8", features = ["debug-embed"] } # Embed in debug to debug WASM.

[build-dependencies]
data_downloader = { version = "0.2", features = ["zip"] }
hex-literal = "0.4"