# Threading requires to compile the standard library with "atomics" and "bulk-memory" features.
# See: https://rustwasm.github.io/wasm-bindgen/examples/raytrace.html#building-the-demo
[toolchain]
channel = "nightly"
components = ["rust-src"]